### ISSUE TITLE
undefined reference to `NtQuerySystemInformation'

### ISSUE THREAD

**Issue by pirouzmoradi** [jungjin0003/ProcessStealth#1]
Hi,
Thanks for your great project.
While compiling I get this error on line 15 and 27:
"ProcessStealth.c|15|undefined reference to `NtQuerySystemInformation'|"
How can I solve this?

**Comment by jungjin0003** [comment]
What compiler did you use?

**Comment by pirouzmoradi** [comment]
gcc compiler in code blocks. now I want to try with mingw

**Comment by jungjin0003** [comment]
Add -lntdll to the gcc compilation option
Ex) `gcc main.c ProcessStealth.c -o main.exe -lntdll`

**Comment by pirouzmoradi** [comment]
Great! it worked. Thanks
