### ISSUE TITLE
changing process

### ISSUE THREAD

**Issue by YoYoGamesYT** [jungjin0003/ProcessStealth#2]
how can we change the process that we want to hide ? i edited the main.c but it doesnt work even with the cmd command its only hiding chrome.exe

**Comment by jungjin0003** [comment]
Did you edit and recompile the main.c?

**Comment by YoYoGamesYT** [comment]
um, no, could you help me doing that bc im not rly sure about how we do that thx by advance =)

**Comment by c0rz** [comment]
undefined reference to `ProcessStealth' error
